require("prototypes.phase-3.category_fixes")
require("prototypes.phase-3.technology")
require("prototypes.phase-3.compatibility.Krastorio2")
require("prototypes.phase-3.compatibility.stack-inserters")
require("prototypes.phase-3.compatibility.elevated-rails")
require("prototypes.phase-3.compatibility.quality")
require("prototypes.phase-3.compatibility.aai-loaders")