require("prototypes.phase-3.category_fixes")
require("prototypes.phase-3.compat.foundry")
require("prototypes.phase-3.compat.electromagnetic-plant")
require("prototypes.phase-3.compat.cryogenic-plant")
require("prototypes.phase-3.compat.Krastorio2")
require("prototypes.phase-3.compat.stack-inserters")
require("prototypes.phase-3.compat.quality")
